import type { ThemePalette } from './types'

// 内建调色板。name 是持久化标识,displayName 给 UI 用。
export const PALETTES: ThemePalette[] = [
  {
    name: 'default',
    displayName: '普鲁士蓝',
    primary: '#4A8FD9',
    onPrimary: '#FFFFFF',
    primaryContainer: '#1A3A66',
    onPrimaryContainer: '#D7E3FF',
    darkBackground: '#0B1A33',
    darkSurface: '#11244A',
    darkSurfaceVariant: '#1A3661',
  },
  {
    name: 'dracula',
    displayName: '德古拉紫',
    primary: '#BD93F9',
    onPrimary: '#282A36',
    primaryContainer: '#44475A',
    onPrimaryContainer: '#F8F8F2',
    darkBackground: '#282A36',
    darkSurface: '#1E1F29',
    darkSurfaceVariant: '#44475A',
  },
  {
    name: 'monokai',
    displayName: '莫诺凯绿',
    primary: '#A6E22E',
    onPrimary: '#272822',
    primaryContainer: '#49483E',
    onPrimaryContainer: '#F8F8F2',
    darkBackground: '#272822',
    darkSurface: '#1E1F1C',
    darkSurfaceVariant: '#49483E',
  },
  {
    name: 'morninglight',
    displayName: '晨曦白',
    primary: '#0969DA',
    onPrimary: '#FFFFFF',
    primaryContainer: '#DDF4FF',
    onPrimaryContainer: '#0A3069',
    darkBackground: '#FAFBFC',
    darkSurface: '#F6F8FA',
    darkSurfaceVariant: '#EAEEF2',
  },
  {
    name: 'warmcream',
    displayName: '米色暖光',
    primary: '#859900',
    onPrimary: '#002B36',
    primaryContainer: '#EEE8D5',
    onPrimaryContainer: '#586E75',
    darkBackground: '#FDF6E3',
    darkSurface: '#F7F0D8',
    darkSurfaceVariant: '#EEE8D5',
  },
  {
    name: 'lightmist',
    displayName: '轻雾灰',
    primary: '#5C6BC0',
    onPrimary: '#FFFFFF',
    primaryContainer: '#E8EAF6',
    onPrimaryContainer: '#1A237E',
    darkBackground: '#F5F5F7',
    darkSurface: '#EBEDF0',
    darkSurfaceVariant: '#DFE2E8',
  },
]

